language: node_js

deploy:
  provider: heroku
  api_key:
    secure: JP4z94IPtmYmUBAnE0+RYJ5B10NcrBw4NRxdWfQ0kOA8GGjFrghytjE3a3AUWfElUBruA6K06dxw1WRutfyM2Fv/N8mL9wE2N0w/8/NoPUakh3GkdukLgek+191M+SgxL9DmZj5XQTqjCsfl8QCwPOpgRoD++jo3pQ07ICtxbHtrgDRJmW0sITJJ68r5heu1LlqRy25ts42ndgctEQPV6/mi4RGnVw18Os+KgMi+RDYSpnULeT5AaZRiNvHhwHfTF+hMIHLBQLrhHwNaJLPySASYThttg8IjOmIFgpO4W65RN5pmwPeJYxw2K9E2Ekgmv8yNyOnwUvDRikr/WFPvf0b24z8ULn2R3D7oIop+ba0ai8DAZ3dTlq0z9NjHhKq+m7+jamFh0AfczGaV4Ch/RGcAVZ8rk1UWJxNNiOGdtGXxI1FiYVpecUH1iJ2mf8RnxZuP7IW2NRhpmN1XyiVGFch0fijGwJxroo0NEsWGxVfRJQRtlvDI+Bd0StAtkcEecde5UONTNrvfSBRK9iektu08nJ7TrkAOhPVzWmqL7VFcS52iAU/kTR7VDzvLT3kDe7iYAhVXmPriG/ujRZb2BaZjy5qMKgV4Pgz1EGERM48Cl/GzN6KXUT3PvDY3AsFRpHIkGx7iP6H+JzjEgoeQn6/iJer4dS58bNGxWRPa17c=
  app: emaily-client
